[tools]
go = "latest"
"go:gotest.tools/gotestsum" = "latest"
"go:actionlint.kjanat.dev/cmd/actionlint" = "latest"
golangci-lint = "latest"

betterleaks = "latest"
typos = "latest"
goreleaser = "latest"

[tasks]

[tasks.app]
description = "Run the application"
run = "go run ./cmd/pronto"

[tasks.debug]
description = "Run the application in debug mode"
run = "go run ./cmd/pronto --debug"

[tasks.test]
description = "Run all tests"
run = "go test ./... -timeout 30s -cover"

[tasks.test_pretty]
description = "Run all tests with pretty output"
run = "gotestsum -- ./... -timeout 30s -cover"

[tasks.test_find_slow]
description = "Find slow tests"
run = "go test -json -count=1 ./... | gotestsum tool slowest --threshold 200ms"

[tasks.test_thorough]
description = "Run all tests many times to look for flakes"
run = "go test -count=100 -timeout 3m ./..."

[tasks.test_thorough_pretty]
description = "Run all tests many times to look for flakes"
run = "gotestsum -- ./... -count=100 -timeout 3m"

[tasks.race]
description = "Run all tests with -race"
run = "go test -count=5 -timeout 2m -race ./..."

[tasks.race_thorough]
description = "Run all tests with -race many times"
run = "go test -count=50 -timeout 2m -race ./..."

[tasks.race_thorough_pretty]
description = "Run all tests with -race many times"
run = "gotestsum -- ./... -count=50 -timeout 2m -race"

[tasks.lint]
description = "Run full golangci-lint"
run = "golangci-lint run ./... --fix"

[tasks.generate]
description = "Run go generate"
run = "go generate ./..."
