// Package gendocs generates pronto's published reference docs
// (docs/events.md, docs/config.md, docs/model.md) from source code and the
// config spec table.
//
// Regenerate with `mise run generate` (go generate ./...). Output is
// deterministic; a staleness test fails when committed docs drift from
// regeneration.
package gendocs

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Files lists the generated documentation file names.
var Files = []string{"events.md", "config.md", "model.md"}

const generatedHeader = `<!-- Code generated by tools/gendocs; DO NOT EDIT. -->
<!-- Regenerate with: mise run generate -->`

// Generate renders every generated doc for the repo at root into outDir.
func Generate(root, outDir string) error {
	internal := filepath.Join(root, "internal")

	eventsDoc, err := renderEvents(filepath.Join(internal, "events"))
	if err != nil {
		return err
	}
	configDoc, err := renderConfig(filepath.Join(internal, "config"))
	if err != nil {
		return err
	}
	modelDoc, err := renderModel(filepath.Join(internal, "model"))
	if err != nil {
		return err
	}

	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return fmt.Errorf("create %s: %w", outDir, err)
	}
	for name, content := range map[string]string{
		"events.md": eventsDoc,
		"config.md": configDoc,
		"model.md":  modelDoc,
	} {
		if err := os.WriteFile(filepath.Join(outDir, name), []byte(content), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
	}
	return nil
}

// writeStructHeading renders one struct as a markdown section with a JSON
// field table. Structs with no exported fields are skipped.
func writeStructHeading(b *strings.Builder, level int, s structDef) {
	if len(s.Fields) == 0 {
		return
	}
	b.WriteString(strings.Repeat("#", level) + " " + s.Name + "\n\n")
	if s.Doc != "" {
		b.WriteString(s.Doc + "\n\n")
	}
	b.WriteString("| Field | JSON | Type | Omitempty | Description |\n")
	b.WriteString("| ----- | ---- | ---- | --------- | ----------- |\n")
	for _, f := range s.Fields {
		json, desc := f.JSON, f.Doc
		if json == "" {
			json = "—"
		}
		if desc == "" {
			desc = "—"
		}
		omitempty := ""
		if f.Omitempty {
			omitempty = "yes"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | `%s` | %s | %s |\n", f.Name, json, f.Type, omitempty, desc)
	}
	b.WriteString("\n")
}
